name: tapyrus-signer-haw
version: git
summary: Tapyrus Signer
description: |
        Tapyrus Signer Node 
license: MIT
base: core18
grade: stable
confinement: strict


apps:
  service:
    command: >-
      tapyrus-signerd
      --config $SNAP_USER_COMMON/signer.toml
    plugs: [network]
    environment:
      HOME: $SNAP_USER_COMMON
    daemon: simple
    restart-condition: always
  daemon:
    command: tapyrus-signerd
    plugs: [network]
  setup:
    command: tapyrus-setup

parts:
  tapyrus-signer:
    source: https://github.com/chaintope/tapyrus-signer.git
    plugin: rust
    build-packages:
      - build-essential
      - m4
      - libgmp3-dev
    stage-packages:
      - libgmp10
